### ISSUE TITLE
[Android] getFlavor() return null in release mode

### ISSUE THREAD

**Issue by CuongNV12** [blvckpvblo/flavor_getter#3]
`String currentFlavor = await FlavorGetter().getFlavor();`
`currentFlavor` return null when run with `--release` flag.

> i do not use Proguard

Please fix it!

**Comment by blvckpvblo** [comment]
Hey,

I'd recommend using Proguard to make it work. There's no workaround so far as Android automatically obfuscates your code by default to shrink the app size.

**Comment by CuongNV12** [comment]
It worked after I added the file 'android/app/proguard-rules.pro'. Thanks for your support!
